server:
  port: 9999

spring:
  application:
    name: users-service

  profiles:
    active: default

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1111
    url: jdbc:h2:tcp://localhost/~/${DATABASE_NAME:ecommerce}

  ## Spring Cloud Server 주소
  ## spring.config.import
  config:
    import: optional:configserver:http://localhost:8888

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.example.service.userservice: DEBUG


#jwt:
#  token:
#    access-expiration: 360000
#  secret:
#    key: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492
