server:
  port: 0

spring:
  application:
    name: users-service

  profiles:
    active: prod
  ## Spring Cloud Server 주소
  ## spring.config.import
  config:

    import: optional:configserver:http://localhost:8888
    name: users-service



  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 1111
    url: jdbc:h2:tcp://localhost/~/${DATABASE_NAME:ecommerce}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

logging:
  level:
    com.example.service.userservice: DEBUG

# Spring Actuator 의 info 와 health 을 제외하고는 모두 비활성화 -> 보안을 위해
# 해당 설정을 통해 활성화 가능
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
#jwt:
#  token:
#    access-expiration: 360000
#  secret:
#    key: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492
