server:
  port: 8761

# Eureka server ? web service ???? ??
spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# ? client ? ???
# - ????? Eureka ?????? ?? ??? Client ? ??
# - ?? ??? ???? ? ???
# - Eureka Server ?? ???? ??