version: "3"
services:
  database:
    image: mariadb:latest
    container_name: ecommerce-system
    ports:
      - 3300:3306
    volumes:
      - ./db/conf.d/ecommerce-service:/etc/mysql/conf.d
      - ./db/data/ecommerce-service:/var/lib/mysql
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    restart: always
