version: "3"
services:
  mariadb01:
    image: mariadb:latest
    container_name: orders-service01
    ports:
      - 3300:3306
    volumes:
      - ./db/conf.d/orders-service01:/etc/mysql/conf.d
      - ./db/data/orders-service01:/var/lib/mysql
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    restart: always

  mariadb02:
    image: mariadb:latest
    container_name: orders_service02
    ports:
      - 3301:3306
    volumes:
      - ./db/conf.d/orders-service02:/etc/mysql/conf.d
      - ./db/data/orders-service02:/var/lib/mysql
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    restart: always

