server:
  port: 0

spring:
  application:
    name: orders-service-02
  ## config server
  config:
    import: configserver:http://localhost:8888
    name: orders-service-02

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}{


logging:
  level:
    com.example.service: DEBUG

topic:
  name: orders-catalogs-topic