server:
  port: 8000

spring:
  application:
    name: spring-api-gateway

  config:
    import: optional:configserver:http://localhost:8888
    ## config-service application 이름의 yml
    name: config-service

  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter

        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, There
                preLogger: true
                postLogger: true
####################################################################################

# 클리이언트의 요청을 받아서 Predicates 을 보고 해당 URL 을 다른 URL 로 요청보낼 수 있다.(원하는 형태로 변경 가능)
# AuthorizationHeaderFilter 는 JWT 검증이 필요한 요청만 거쳐야 한다.

        ### 유저 서비스 헬스 체크
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/users/health-check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        ### 유저 회원가입
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}

        ### 유저 로그인
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}

        ### 유저 설정 정보
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/users/config
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service(?<segment>.*), /$\{segment}

        ### USERS-SERVICE Actuator
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service(?<segment>.*), /$\{segment}

        ### 유저 관련 일반 기능
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-service/(?<segment>.*), /$\{segment}
            # jwt 인증 관련 필터
            - AuthorizationHeaderFilter

####################################################################################
        - id: catalogs-service
          uri: lb://CATALOGS-SERVICE
          predicates:
            - Path=/catalogs-service/**
          filters:
            - RewritePath=/orders-service/(?<segment>.*), /$\{segment}
####################################################################################
        - id: orders-service-01
          uri: lb://ORDERS-SERVICE-01
          predicates:
            - Path=/orders-service-01/**
          filters:
            - RewritePath=/orders-service-01/(?<segment>.*), /$\{segment}
####################################################################################
        - id: orders-service-02
          uri: lb://ORDERS-SERVICE-02
          predicates:
            - Path=/orders-service-02/**
          filters:
            - RewritePath=/orders-service-02/(?<segment>.*), /$\{segment}

      # global filter 부분
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"