server:
  port: 8000

spring:
  application:
    name: spring-api-gateway

  cloud:
    gateway:
      routes:
        - id: first-service
#          uri: http://localhost:8081
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter

        - id: second-service
#          uri: http://localhost:8082
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, There
                preLogger: true
                postLogger: true

        - id: user-service
          uri: lb://USERS-SERVICE # data 을 forwarding 할 eureka server
          predicates:
            - Path=/users-service/** # 실제 클라이언트의 요쳥 형식
        ## 결국 /user-service/** 로 요청이 들어오면 USER-SERVICE eureka 로 forwarding

      # global filter 부분
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
  main:
    web-application-type: reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka



