server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          # github address
          uri: https://github.com/choidongkuen/spring_cloud_config_repo